@host=http://localhost:5550

### Register
Post {{host}}/api/Accounts/Register
Content-type: application/json

{ 
  "Name" : "Ikhtisham",
   "email": "Ali",
  "password": "Adkjfkd@123455"
  
}

### Log in
Post {{host}}/api/Accounts/Login
Content-type: application/json

{ 
  "email": "string",
  "password": "string"
} 



